# This is a basic workflow to help you get started with Actions

name: Check for new commits

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  check:
    runs-on: ubuntu-latest
    env:
      CONTEXT_GITHUB: ${{ toJson(github) }}
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      # setup python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
    
      # Configure pip caching
      - uses: actions/cache@v3
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      # Intall Python dependencies
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      # Run checks
      - name: Run commit check
        run: | 
          output=$(python check_commits.py)
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}"
          echo "::set-output name=commit_info::$output"
        id: commit_check
        
      # Print output  
      - name: Print commit check info
        run: |
          echo "${{ steps.commit_check.outputs.commit_info }}" > commit_check.txt
          cat commit_check.txt    
